name = "simple"
license = "MIT"
licenselink = "https://github.com/iberryful/simple/blob/master/LICENSE"
description = "Sinple theme for Hugo."
homepage = "https://github.com/iberryful/simple"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = ["blog"]
min_version = "0.50"

